---
layout: post_layout
title: 智能合约审计-重入攻击漏洞
time: 2019年12月19日 星期四
location: 合肥
pulished: true
excerpt_separator: "#"
---

描述：漏洞合约中某个函数中，使用call()方法发送eth,若eth的接收者为一个合约地址，则会触发该合约的fallback()函数。若该合约是攻击者的恶意合约，攻击者可以在fallback()函数中重新调用漏洞合约的上述函数，导致重入攻击

核心问题：重要的合约变量在“重入”的过程中没有被修改，从而绕过了限制

# Fallback函数

概念:
    回退函数，是合约里的特殊无名函数，有且仅有一个。它在合约调用没有匹配到函数签名，或者调用没有带任何数据时被自动调用。

触发场景：

- address.send(ether_to_send)
   
- address.call().value(ether_to_send)
    
# 漏洞流程
![](/assets/demo/chongru.png)

```java
/**
 * 保存上一次请求的结果
 */
var lastResult = Result.SUCCESS

/**
 * 已经加载好的页面号
 */
var loadedPageIndex = -1

/**
 * 当前正在加载的页面, 在页面加载完成后, 就会被置为 -1
 * 所以用它来判断是否正在加载,
 */
var loadingPageIndex = -1
```
